### ISSUE TITLE
CSP getting violated for WebComponentsIcons

### ISSUE THREAD

**Issue by Sujoy-Banerjee** [telerik/kendo-angular#1724]
## I'm submitting a...

* Bug report 

## Current behavior
Once CSP (Content Security Policy) is enabled CSP violation error displayed in browser while application tries to download **WebComponentsIcons** where  Request URL is something like this  **data:font/ttf;base64,.......**
I have copied WebComponentsIcons locally in assets directory and locating it by ,

```scss
@import '../node_modules/@progress/kendo-theme-default/scss/all';                 
@font-face {
  font-family: 'WebComponentsIcons';
  font-style: normal;
  font-weight: normal;
  /* For IE6-8 */
  src: url('./assets/fonts/WebComponentsIcons.eot') format( "truetype");
  src: url('./assets/fonts/WebComponentsIcons.woff') format('woff'), 
    url('./assets/fonts/WebComponentsIcons.ttf') format('truetype'), 
   url("./assets/fonts/WebComponentsIcons.svg") format("svg");
 }
```

By doing this I can see that icons are getting loaded properly but CSP error is displayed.
Also noticed that following font face deceleration still there in bundle CSS file which I think causing this issue.

`@font-face {
    font-family: WebComponentsIcons;
    font-style: normal;
    font-weight: 400;
    src: url(data:font/ttf;base64,AAEA.....
}` 

## Expected behavior

CSP should not be violated and proper direction to include fonts should be present.   

## Minimal reproduction of the problem with instructions
I was not able to create a Plunker for this, but if we run [kendo-angular-csp](https://github.com/tsvetomir/kendo-angular-csp) application  we can see the CSP error.
## Environment

Package versions:

```
   "@angular/animations": "^5.2.9",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.11",
    "@angular/core": "^5.2.11",
    "@angular/forms": "^5.2.11",
    "@angular/http": "^5.2.11",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "^5.2.11",
    "@angular/platform-browser-dynamic": "^5.2.11",
    "@angular/router": "^5.2.11",
    "@progress/kendo-angular-buttons": "^4.1.0",
    "@progress/kendo-angular-intl": "^1.0.0",
    "@progress/kendo-angular-l10n": "^1.0.0",
    "@progress/kendo-angular-dateinputs": "^3.3.0",
    "@progress/kendo-angular-dropdowns": "^3.0.0",
    "@progress/kendo-angular-excel-export": "^2.0.0",
    "@progress/kendo-angular-grid": "^3.3.0",
    "@progress/kendo-angular-inputs": "^3.1.1",
    "@progress/kendo-data-query": "^1.1.0",
    "@progress/kendo-drawing": "^1.4.0",
    "@progress/kendo-theme-default": "^2.32.0",
    "@progress/kendo-angular-charts": "^3.3.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
```

Browser:

- Chrome (desktop) version Version 67.0.3396.99 (Official Build) (64-bit)

System:
- TypeScript version: **5.6.0**
- Node version: Node: **v8.11.3** , NPM: **5.6.0**
- Platform:  **Windows**
