### ISSUE TITLE
The grid's groups overflow 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1810]
## I'm submitting a...
* Bug report 

## Current behavior
When there is no space in the grid's header to hold all group fields they overflow:

![2018-09-21_1348](https://user-images.githubusercontent.com/20015190/45876993-1129b680-bda5-11e8-9d82-05ab1e101ecc.png)

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-9pshov?file=app%2Fapp.component.ts](https://stackblitz.com/edit/angular-9pshov?file=app%2Fapp.component.ts)

## Workaround

We could add one of the following styles:

```scss
.k-grouping-header {
    flex-wrap: wrap;
}

.k-grouping-header {
    overflow: auto;
}
```
