### ISSUE TITLE
SplitterPane: Height not set when using FlexBox when splitterPane is collapsed

### ISSUE THREAD

**Issue by SchneiderMK** [telerik/kendo-angular#1978]
## I'm submitting a...

* Bug report 

## Current behavior

When I use FlexBox and the Splitter, the SplitterPane is not collapsed correctly. The height of the collapsed pane is not set.

## Expected behavior

Height should calculated correct to hide collapsed pane.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/kendo-angular-splitter-demo
1) check the height of the details-bottom pane
2) collapse bottom pane
3) check height again. Height is not set to 0. Pane is visible but should be hidden.

## Environment

Browser:

- Chrome (desktop) version  70.0.3538.110

System:
- See StackBlitz

**Comment by gyoshev** [comment]
Thank you for reporting this. A workaround until this is fixed in the themes is to add the following global CSS to the page:

```css
.k-splitter-flex .k-pane.k-state-hidden,
.k-splitter-flex .k-pane[hidden],
.k-splitter-flex .k-pane-flex.k-state-hidden,
.k-splitter-flex .k-pane-flex[hidden] {
  flex-grow: 0 !important;
}
```
