### ISSUE TITLE
[Editor] Scrollable "View source" dialog in the editor

### ISSUE THREAD

**Issue by siyka-marinova** [telerik/kendo-angular#2584]
The "View source" dialog is not scrollable and, in most cases, it is necessary to use arrow down to view the complete html.
It will be convenient be able to use scrolling for longer html content.

**Comment by lucasheight** [comment]
Just want to and a "me too"  to this and I have a simple stackblitz to show the problem.
https://stackblitz.com/edit/angular-zbtnqu?file=app/app.component.ts

**Comment by mbechev** [comment]
@lucasheight, thank you for sharing a **StackBlitz** that shows the issue.

As a workaround a custom CSS styles could be applied to the dialog content:

```css
.k-editor .k-dialog-content .k-editor-textarea {
    overflow-y: scroll;
    resize: none;
}
```
Here is an example:
https://stackblitz.com/edit/viewsource-overflow?file=index.html
