### ISSUE TITLE
PDF Export not correct

### ISSUE THREAD

**Issue by Toso82** [telerik/kendo-angular#2772]
**Describe the bug**
I'm test your component and not export well.  Not generate A4 in the correct dimension or not well. 
How can i fix? 

**To Reproduce**

- https://toso82g.github.io/TestAg9
- Just click "Genera PDF"

**Expected behavior**

**Screenshots**

**Browser**
 - OS: Windows 10
 - Browser Chrome
 - Version 82.0.4069.0 (Build ufficiale) canary (a 64 bit)

**Additional context**
This is a test project in my repository:
https://toso82.github.io/TestAg9/

**Comment by tapopov** [comment]
The repository is for bug reports only. Please [check the documentation](https://www.telerik.com/kendo-angular-ui/components/pdfexport/content-styling/) or open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.

**Comment by Toso82** [comment]
Sorry but this is a but not export correct. You see the example

**Comment by tapopov** [comment]
@Toso82 
The content has an offset and is bigger than expected for an A4 paper size. Adjusting the content size or scaling it down will produce the expected results ([example](https://stackblitz.com/edit/angular-3nfn2k?file=app/app.component.ts)). Again, this is a configuration issue, not a bug in the PDF export.

**Comment by Toso82** [comment]
@tapopov  

Sorry but your example it is a bit difference. I try to recreate a small one and i notice that there is a problem on pdf export:

https://stackblitz.com/edit/angular-d1syfo

There is :

```html
 <button (click)="pdf.saveAs('invoice.pdf')">
        Save As PDF...
</button> 

<kendo-pdf-export #pdf paperSize="A4">
  <div class="pageSize gridLayout">
      <div class="gridItem"></div>
      <div class="gridItem"></div>
  </div>
</kendo-pdf-export>

```

```css
.pageSize {
 height: 29.6cm;
 width:21cm;  
}

.gridLayout {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr;
  
  justify-items: stretch;
  align-items: stretch;
  gap:20px;
}

.gridItem {
  background-color: red;   
}
```
Nothing so complex   and not export well
