### ISSUE TITLE
Undesired gap between list items when default item is set in adaptive mode

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4563]
### Description

When setting the [defaultItem](https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/default-item) of the DropDownList and enabling adaptive mode, а huge gap appears between the default item and the rest of the options from the list:

<img width="455" alt="Image" src="https://github.com/user-attachments/assets/6594018f-1fbb-4041-ab8d-2b6d859fb960" />

If `defaultItem` is not being set, the list item layout looks ok. 

The KendoReact DropDownList also renders the default item correctly in adaptive mode:

https://stackblitz.com/edit/react-lkjcjwh6?file=app%2Fapp.jsx

<img width="539" alt="Image" src="https://github.com/user-attachments/assets/b9bf48fc-80df-4924-8fcf-6b0e6b81c6ef" />

### Steps To Reproduce

Open the DropDownList in smaller screen resolution:
https://stackblitz.com/edit/angular-njpjstum?file=src%2Fapp%2Fapp.component.ts

### Actual Behavior

The gap appears when `defaultItem` is set.

### Expected Behavior

The options layout should be unchanged when `defaultItem` is set.

### Workaround

A possible workaround is to overwrite the CSS styles such as:

```css
      .k-actionsheet-content {
            .k-list-container:has(:nth-child(2)) > :first-child {
                flex-basis: 2.25rem;
                flex-grow: 0;
            }
        }
```
https://stackblitz.com/edit/angular-njpjstum-lnj3xcc7?file=src%2Fapp%2Fapp.component.ts
