### ISSUE TITLE
Misaligmnet caused by date header template

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-angular#4574]
### Description

Customizing the [date header template](https://www.telerik.com/kendo-angular-ui/components/scheduler/templates#date-headers) of the Scheduler causes misalignment when the custom content is displayed on several lines which expands the cell height.

### Steps To Reproduce

Use `kendoSchedulerDateHeaderTemplate` to customize the date header cell content.  The content should be on multiple lines
https://stackblitz.com/edit/angular-xw1x4ile?file=src%2Fapp%2Fapp.component.ts

### Actual Behavior

It looks like the header cells correctly expanded its height, but the decorative `<th>` element in the times part doesn't recognize the change and stays as is:

<img width="734" alt="Image" src="https://github.com/user-attachments/assets/166d8f8a-fa6d-4a73-8ed1-8ca84d9ee127" />

This causes misalignment with the scheduler's all-day slot.

### Expected Behavior

There should be no misalignment issues and all header cells must be equal in height.

### Browser

Chrome

### Browser version

latest

### OS type

MacOS

**Comment by HaberkornJonas** [comment]
If the height of the `kendoSchedulerDateHeaderTemplate` is dynamic, a fixed height might no be appropriated.

I'm not a fan of absolute positioning but this should do the trick for a temporary workaround:

```css
multi-day-view .k-scheduler-weekview .k-scheduler-head{
  position: relative;
}

multi-day-view .k-scheduler-weekview .k-scheduler-head>td{
  border-right-width: 1px;
  border-right-style: solid;
}

multi-day-view .k-scheduler-weekview .k-scheduler-head .k-scheduler-times{
  position: absolute;
  bottom: 0px;
}

multi-day-view .k-scheduler-weekview .k-scheduler-head .k-scheduler-times th{
  border-right-width: 0px;
}
```

https://stackblitz.com/edit/angular-xw1x4ile-eqgyfwjh?file=src%2Fstyles.css
