### ISSUE TITLE
Overlapping list items in adaptive actionsheet nested in `kendo-grid`

### ISSUE THREAD

**Issue by dboryga-gecos** [telerik/kendo-angular#4590]
### Description

After opening the adaptive dropdown within the 'kendo-grid' component, all items appear on top of each other.

The issue is due to the following styles:
```css
/* _layout.scss */
.k-virtual-list .k-list-group-item, {
    position: absolute;
    width: 100%;
}
```

I resolved the issue in my project by overwriting the position property for the time being:
```css
.k-adaptive-actionsheet .k-list-item {
  position: static;
}
```

### Steps To Reproduce

1. Use the `kendo-grid` component
2. In a cell, use the `kendo-dropdownlist` with `adaptiveMode="auto"`

### Screenshots or video

![Image](https://github.com/user-attachments/assets/d78abb11-bc17-4b52-89b4-f25e0026ce1e)

![Image](https://github.com/user-attachments/assets/018c7f20-d807-46d9-8112-ae8ec128b81c)

### Actual Behavior

All items have `position: absolute`, which results in displaying all of them on top of each other.

### Expected Behavior

Items should be displayed as a list (without `position: absolute`)

### Browser

Chrome

### Browser version

latest

### OS type

Windows
