### ISSUE TITLE
Double shadow in focused DatePicker and TimePicker styling

### ISSUE THREAD

**Issue by JaapMosselman** [telerik/kendo-angular#916]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
DatePicker and TimePicker use a nested DateInput component.
In the default KendoUI stylesheet there is a style to to disable the border of that nested component:

```css
.k-datepicker .k-dateinput-wrap,
.k-datetimepicker .k-dateinput-wrap,
.k-timepicker .k-dateinput-wrap {
    border: 0;
    border-radius: 2px 0 0 2px;
}
```

Here box-shadow should also be set to none.

In this image you can see that the shadow below the input is darker than below the toggle button:
![datepicker shadow](https://user-images.githubusercontent.com/22192317/30445548-9b740636-9986-11e7-82de-5397184b4fda.PNG)

## Expected behavior
No double shadow

## Minimal reproduction of the problem with instructions
See standard demo:
http://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/

## What is the motivation or use case for changing the behavior?
Little better UX.

## Environment
Browser:
- Chrome (desktop)
- Edge
