### ISSUE TITLE
Grid columns and headers misaligned after window resizing in IE

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#956]
The Grid headers are not resized properly in IE when the page becomes smaller than the width of the Grid and a horizontal scrollbar appears. As a result the headers get misaligned with the columns:

https://plnkr.co/edit/9I9KxGqw5IpOLzKWxIJo?p=preview

https://www.screencast.com/t/CC6os2g5w

**Comment by tsvetomir** [comment]
The problem is reproducible with just the Grid markup and no JavaScript, [see plunkr](https://plnkr.co/edit/JXu8Weg7nq1cvcQb8lYF?p=preview).

**Comment by gyoshev** [comment]
After some digging, we found that the problem is caused by the `position: absolute` of the content `<table>` element in the virtualized grid. A workaround for this is to apply the following styles:

```css
.k-grid-virtual .k-grid-content .k-grid-table,
.k-grid-virtual .k-grid-content > table {
    position: relative;
    float: left;
    z-index: 1;
}

.k-grid-virtual .k-grid-content > .k-height-container {
    position: relative;
    float: left;
}

.k-grid-virtual .k-grid-content::after {
    content: "";
    display: block;
    clear: both;
}
```
